### ISSUE TITLE
Reorder intents list

### ISSUE THREAD

**Issue by mikbry** [Opla/front#15]
This feature was broken longtime ago but we need to add it again.

**Comment by mikbry** [comment]
Ok it works on client side. But when you refresh the page, all is gone... In prehistoric releases, using a mem/file storage, the reordering was stored on server. but now with Mysql it is getting more complex to reorder.

**Comment by willdurand** [comment]
hum good catch although it is fixed in this project, the API needs to be fixed then. So I am going to close this issue and open a new one on the backend.
