### ISSUE TITLE
Make it clear that current master deployed on k8s (qa) version is a test version

### ISSUE THREAD

**Issue by licarth** [Opla/front#160]
Make it possible to configure the frontend (through an ENV variable passed to the docker container, and/or an entry in `default.json`) to display a banner at the top of the page that clearly says that this version is a test/demo version and that people should not store anything personal or sensitive in it.

Banner may contain : 
- The commit id of currently deployed `front` (with a link to github)
- A message saying this is a test environment

**Comment by mikbry** [comment]
See
https://github.com/Zoapp/front/issues/69
