### ISSUE TITLE
QA instance : playground don't work

### ISSUE THREAD

**Issue by mikbry** [Opla/front#162]
### When
 - Create a new chatbot with a template
- go in playground say Hello
- Bot don't response
![screen shot 2018-05-28 at 19 11 15](https://user-images.githubusercontent.com/395718/40624119-f19ba0bc-62aa-11e8-8547-ecfacef86190.png)
### Todo
 - It should respond . Works in dev versions

**Comment by licarth** [comment]
This seems flaky, it currently works for me. Any error ?

**Comment by mikbry** [comment]
No errors at all

**Comment by mikbry** [comment]
I retry on my other PC. Account can't log in. But with a new account it is ok.

**Comment by mikbry** [comment]
Today it works on my Mac ...

**Comment by mikbry** [comment]
Marie just created an empty chatbot, and she got the same error. Nothing in the console

**Comment by licarth** [comment]
That is interesting. I have no idea why this is not working right now, despite having had a look at the logs. I don't see any error in the Frontend, neither in the backend. Websockets work because they do receive messages, but they seem to receive only messages that have been sent by the user.

**Comment by mikbry** [comment]
even the publsh page doesn't work...

**Comment by licarth** [comment]
Yeah, it seems to be related, when one does not work, the other does not either.

**Comment by lunika** [comment]
And if you restart the backend what happen ? I noticed sometimes that when I made a modification in my code, the watcher restart the server and then I have no problem. So maybe it is an other initialization problem.
Lot of thing are initialized and then live in memory (openNLX for example) so you have to maintain a "state" in memory, if you forget to do it you can have unwanted behaviour.

**Comment by licarth** [comment]
I did try to restart the backend, and it does not seem to work. (even though in the past, it did seem to work).
A bit of debugging tells me that `openNLX.js:OpenNLXMiddleware#onDispatch` doesn't get called on new messages when this problem happens. But a `"sandbox"` event does get dispatched.

**Comment by licarth** [comment]
Restarted backend on prod, seems to have fixed it. However, does not explain where it comes from.

**Comment by mikbry** [comment]
This issue could be related to dispatch async. This PR could have fix it:
https://github.com/Opla/backend/pull/72

**Comment by mikbry** [comment]
It is not a dispatch async problem. The bug is back...
