### ISSUE TITLE
Publish webpage don't work the 1st time

### ISSUE THREAD

**Issue by mikbry** [Opla/front#163]
### When
- Create a chatbot
- Publish it
- Go to published page
- A blank screen, with this error:
![screen shot 2018-05-28 at 19 13 51](https://user-images.githubusercontent.com/395718/40624182-49c78c10-62ab-11e8-9a16-895a36b6b84b.png)
### TODO
- it should display webchat as in dev version.

**Comment by licarth** [comment]
Same, works for me right now : 
![image](https://user-images.githubusercontent.com/5550241/40624546-9c9ce0c8-62ad-11e8-9396-95e9811098ea.png)

**Comment by licarth** [comment]
This and https://github.com/Opla/front/issues/162 seem flaky.  Need to be debugged when happens again.

**Comment by mikbry** [comment]
In fact it is a publish bug if you create a new bot. go to publish, and then click on webapp link the publish page display this error.

**Comment by lunika** [comment]
I partially reproduce it. Sometimes I have this error but if I follow exactly the same scenario again I will don't have it... Sometimes data are missing in parameters table

**Comment by mikbry** [comment]
This issue could be related to dispatch async. This PR could have fix it:
https://github.com/Opla/backend/pull/72

**Comment by mikbry** [comment]
This issue seems to be fixed, but I will close it end of this week.
