### ISSUE TITLE
Publish webpage : stucked on Loading

### ISSUE THREAD

**Issue by mikbry** [Opla/front#164]
### When
Sometime the first time you want to configure web page it displays, and nothing more : 
![screen shot 2018-05-29 at 08 30 26](https://user-images.githubusercontent.com/395718/40641702-d668840c-631a-11e8-894e-958b997b39cc.png)
- Create a chatbot
- Login
- Publish
- Select webpage click to setup
- The dialog is stucked on Loading stage
### TODO
- Display webpage settings

**Comment by lunika** [comment]
this page should not be display while the charbot is not published. You can't info until the publish process is done.
