### ISSUE TITLE
QA Instance : need publicUrl set

### ISSUE THREAD

**Issue by mikbry** [Opla/front#202]
![screen shot 2018-06-08 at 17 07 08](https://user-images.githubusercontent.com/395718/41165713-9fc51b32-6b3e-11e8-9472-5566d60d57d2.png)
In the table Parameters :
set a row with:
name=backend
value={publicUrl: "XXX"}
Where XXX is the http://api.xxx.domain Url
Also Api and Auth domain url is undefined

**Comment by mikbry** [comment]
In zoapp/backend it is defined on the fly from config file, see admin.js:
`
parameters.backend.apiUrl = [
        `${cfg.global.api.ip}:${cfg.global.api.port}`,
        cfg.global.api.endpoint,
        `/${cfg.global.api.version}/`,
      ].join("");
`

`
parameters.backend.authUrl = [
        `${cfg.global.api.ip}:${cfg.global.api.port}`,
        `${cfg.auth.api.endpoint}/`,
      ].join("");
`

So global.api.ip is missing.

**Comment by licarth** [comment]
This issue was moved to Opla/opla#45
