### ISSUE TITLE
Bug with brackets into the entity

### ISSUE THREAD

**Issue by williamdaconceicao** [Opla/front#26]
Context
On a Windows 10 computer, with google chrome installed
The command block, look like an single entity.

What are you trying to achieve or the steps to reproduce ?
Adding a closed bracket into the entity.

Which result you had ?
The closed bracket is written outside of the entity.

![capture](https://user-images.githubusercontent.com/22961990/36717296-d23561d0-1b9d-11e8-98b7-56bc64924c2f.PNG)

TODO
Check if the code of the entities have an exceptions for the closing brackets.

**Comment by david-talabard** [comment]
A same problem is present on  other section : 
![image](https://user-images.githubusercontent.com/7806831/37782553-738305a8-2df3-11e8-8f43-00b39cd6bcb3.png)
