### ISSUE TITLE
Bug with the publish button

### ISSUE THREAD

**Issue by williamdaconceicao** [Opla/front#27]
Context
On a Windows 10 computer, with google chrome installed

What are you trying to achieve or the steps to reproduce ?
Try to switch tabs between intents and entities.

Which result you had ?
The publish button move to the left about 20px.
Note: this bug appear 5 times out of 10

TODO
Make the website responsive with grid use will fix that.

**Comment by willdurand** [comment]
I think this will be fixed in the next release of material-components-web.

**Comment by willdurand** [comment]
Ah well looks like it is a wontfix since it was due to react-mdl.
