### ISSUE TITLE
Clicking on builder tab shows blank screen

### ISSUE THREAD

**Issue by licarth** [Opla/front#288]
Sometimes, clicking on the builder tab shows a blank screen.

To reproduce, try to login with:
user: thomascarli
password:  xxxx

![peek 16-08-2018 10-34](https://user-images.githubusercontent.com/5550241/44197864-24ab8700-a140-11e8-8b0c-469d4d24e257.gif)

**Comment by licarth** [comment]
So, it consistently happens with the following user :
thomascarli / EwteebQueorfir4

**Comment by mikbry** [comment]
Line 100 of ActionsList, it doesn't check if actions[0] is not null.
But why actions[0] could be null I don't know how it occurs.
