### ISSUE TITLE
Create panel is broken

### ISSUE THREAD

**Issue by willdurand** [Opla/front#30]
The create bot panel does not work anymore, there are errors related to the `Zrmc.open()` and the "advanced settings" button does not do anything anymore.

**Comment by willdurand** [comment]
ah it seems I had to use `Zrmc.showDialog()`

**Comment by mikbry** [comment]
Strange I thought I fixed any of these types of errors ;-)

**Comment by willdurand** [comment]
np, it is always good to have a second look :)
