### ISSUE TITLE
Publish Dialog : Regression click on switch doesn't work

### ISSUE THREAD

**Issue by mikbry** [Opla/front#31]
Click on switch activate a messaging platform to publish on. But it doesn't work any more.
Was working on previous version of Opla CE.
<img width="622" alt="screen shot 2018-02-27 at 21 19 45" src="https://user-images.githubusercontent.com/395718/36752710-2b37d996-1c04-11e8-9348-66ea6b913d3f.png">

**Comment by mikbry** [comment]
onChange in Switch component disapeared, or I ever dreamed of it ?

**Comment by willdurand** [comment]
xref https://github.com/Zoapp/react-materialcomponents/issues/53
