### ISSUE TITLE
Cannot create intent

### ISSUE THREAD

**Issue by willdurand** [Opla/front#43]
It says "cyclic object value" in the bottom toast but nothing more when trying to "create intent".

**Comment by mikbry** [comment]
I saw this bug, also there is a warning in console:
Warning: Failed prop type: Invalid prop `error` of type `string` supplied to `App`, expected `object`.
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App))
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
    in AppContainer

In fact it sounds like an error in zoapp/front see src/containers/App.jsx line 46

**Comment by willdurand** [comment]
oh ok, I'll investigate then. I was trying to fix this bug today but the lack of proper webpack HMR made me a little bit sad, so I fixed the config first and now I can back to fixing bugs 🚒

**Comment by willdurand** [comment]
Ok so the bug comes from `getFieldValue()` (zrmc?) not returning a value but a React object.
