### ISSUE TITLE
Implements errors visual display bot creation / signin

### ISSUE THREAD

**Issue by mikbry** [Opla/front#53]
When create bot, signin, server disconnected.
Actually a snackbar display.
We need to display error in a more helpful manner. In textfield were the error occurs for example.

**Comment by JulienUsson** [comment]
Errors are find at api call. Do you want a pre api call verification? for exemple if email is correct ? etc?
Can i change the api to return more detailled errors?

**Comment by mikbry** [comment]
pre-api call. check email and others fields. But inputs could handle that. 
Changing api calls it is in zoapp/zoauth repo. So at first pre-verifications. Then create an issue in zoauth.

**Comment by JulienUsson** [comment]
* Are all fields required for createAssistant?
 * I have an error in the console when i use the language Select, i create a new issue for that?

**Comment by mikbry** [comment]
And for signin and others users call. It should be fixed in zoapp/front

**Comment by JulienUsson** [comment]
`Changing api errors returns, it is in zoapp/zoauth repo.` => Api return for createAssistant is in Opla/backend, no?

**Comment by mikbry** [comment]
Yes all inputs are used. Language is english by default.
For language select don't open a new issue. Or if it is at a lower level open an issue in corresponding repo (for select component in ZRMC)

**Comment by mikbry** [comment]
createAssistant is in Opla/backend right

**Comment by JulienUsson** [comment]
Can i have to create an issue for each PR? Because i have to make a PR for Opla/backend part, Zoapp/zoauth part, etc...

**Comment by mikbry** [comment]
No
