### ISSUE TITLE
Blank screen after two login fail

### ISSUE THREAD

**Issue by JulienUsson** [Opla/front#54]
**Context**
On a Windows 7 computer, with google chrome installed

**What are you trying to achieve or the steps to reproduce ?**
Login with wrong user/password twice

**Which result you had ?**
Blank screen page

[localhost-1520859047284.log](https://github.com/Opla/front/files/1802770/localhost-1520859047284.log)

**Comment by mikbry** [comment]
All logins logic / ui are in zoapp/front. So you need to move this issue to this repo.

**Comment by JulienUsson** [comment]
https://github.com/Zoapp/front/issues/38
