### ISSUE TITLE
Codacy complain about func = (param) => {...}

### ISSUE THREAD

**Issue by mikbry** [Opla/front#65]
Our code is styled like that:
`func = (param) => {...};`

But Codacy complain about that and prefer:
`func = param => {...};`

We need to fix codacy.

**Comment by mikbry** [comment]
yep

**Comment by mikbry** [comment]
After investigating there is a problem with arrow-parens in Codacy, It is configured ok in eslintrc.json:
`"arrowParens": "always"`

**Comment by willdurand** [comment]
`arrowParens` is an option available as of Prettier 1.9, but Codacy uses 1.7 (https://github.com/codacy/codacy-eslint/blob/80d960d3c917d518a2c50fb5bc908a77e33086aa/build.sbt#L75) and do not install the project dependencies...

**Comment by mikbry** [comment]
https://github.com/codacy/codacy-eslint/issues/88
