### ISSUE TITLE
bad rendering on firefox when creating a new virtual assistant

### ISSUE THREAD

**Issue by lunika** [Opla/front#67]
On firefox, the icon for the template when I create a new assistant are not well rendered. The icon is very small if you compare with Chrome

![screenshot from 2018-04-09 10-04-52](https://user-images.githubusercontent.com/767834/38486623-dc25dbba-3bdd-11e8-80ea-de944cdf3663.png)

**Comment by mikbry** [comment]
We need to follow MD style for displaying:
https://material.io/guidelines/components/grid-lists.html#grid-lists-specs

And this display format:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B_udO5B8pzrzQnd1TmFpRHlENUU/components-grids-specs13.png

**Comment by Craaftx** [comment]
I work on it
