### ISSUE TITLE
Dashboard : display "No data" when no data available

### ISSUE THREAD

**Issue by mikbry** [Opla/front#75]
<img width="1383" alt="screen shot 2018-04-16 at 18 49 36" src="https://user-images.githubusercontent.com/395718/38823563-06608a5a-41a7-11e8-8e9b-9215c01e350c.png">

Instead of blank fields, "ms" or "NaN%", we should display "No data" in red #F44336. Like this:

<img width="1080" alt="screen shot 2018-04-16 at 19 02 37" src="https://user-images.githubusercontent.com/395718/38824206-cc715048-41a8-11e8-95f1-a607d809cbef.png">

**Comment by Craaftx** [comment]
Issue repair with https://github.com/Opla/front/pull/76
