### ISSUE TITLE
Create : wrong path for templates and languages

### ISSUE THREAD

**Issue by mikbry** [Opla/front#82]
### When
You go to create page
In console log I got error 500 with these paths
http://localhost:8081/api/v1//admin/templates
http://localhost:8081/api/v1//admin/languages

### Fix
remove extra '/'

**Comment by lunika** [comment]
you should have a 404 and not 500 if it's a path issue IMO

**Comment by mikbry** [comment]
right, but the path is not ok. And not sure if my dependencies are ok for the error 500, I check.

**Comment by mikbry** [comment]
For error 500 the response is : {"error":"Only absolute URLs are supported","stack":"TypeError: Only absolute URLs are supported\n    at getNodeRequestOptions (/opla-backend/node_modules/node-fetch/lib/index.js:1284:9)\n    ...
