### ISSUE TITLE
ActionsToolbox : add condition button

### ISSUE THREAD

**Issue by mikbry** [Opla/front#89]
## Where
<img width="89" alt="screen shot 2018-04-23 at 22 57 29" src="https://user-images.githubusercontent.com/395718/39152833-cb3e40e0-4749-11e8-92d4-a2293853bc9a.png">
Using icon name="device_hub"

## Behaviour
Add a condition to a new output
Transform a text output to a condition
See #88

**Comment by lodelestra** [comment]
Condition is available by default in new output. User is free to set conditions name and value or not. Then it's saved depending of which data are available.
