### ISSUE TITLE
Create : change texts

### ISSUE THREAD

**Issue by mikbry** [Opla/front#93]
## Changes
Change title name : create your conversational robot
Change Welcome texts
Remove text bellow templates
Rename button "Let's go !" by "Opla !"
Remove button "advanced settings"

## Like that
![screen shot 2018-04-24 at 09 58 18](https://user-images.githubusercontent.com/395718/39173837-23cd1108-47a6-11e8-8732-3c575a220f70.png)

**Comment by Craaftx** [comment]
This is corrected : https://github.com/Opla/front/pull/100
